Switch a few bits for cross-variant consistency

diff --git a/1.5/alpine/Dockerfile b/1.5/alpine/Dockerfile
--- a/1.5/alpine/Dockerfile
+++ b/1.5/alpine/Dockerfile
@@ -1,33 +1,85 @@
-FROM alpine:3.4
+FROM openjdk:8-jre-alpine
 
+# ensure logstash user exists
 RUN addgroup -S logstash && adduser -S -G logstash logstash
 
-RUN echo '@testing http://nl.alpinelinux.org/alpine/edge/testing' >> '/etc/apk/repositories'
+# install plugin dependencies
+RUN apk add --no-cache \
+# env: can't execute 'bash': No such file or directory
+		bash \
+		libzmq
 
-RUN apk update
-RUN apk add --no-cache ca-certificates curl openjdk8 gosu@testing libzmq
+# grab su-exec for easy step-down from root
+RUN apk add --no-cache 'su-exec>=0.2'
 
-# the "ffi-rzmq-core" gem is very picky about where it looks for libzmq.so
-RUN mkdir -p /usr/local/lib \
-	&& ln -s /usr/lib/*/libzmq.so.3 /usr/local/lib/libzmq.so
+# https://www.elastic.co/guide/en/logstash/5.0/installing-logstash.html#_apt
+# https://artifacts.elastic.co/GPG-KEY-elasticsearch
+ENV GPG_KEY 46095ACC8548582C1A2699A9D27D666CD88E42B4
 
-ENV LOGSTASH_MAJOR 1.5
+ENV LOGSTASH_PATH /opt/logstash/bin
+ENV PATH $LOGSTASH_PATH:$PATH
+
 ENV LOGSTASH_VERSION 1.5.6
-ENV LOGSTASH_TAR_SHA1 f3e4342f496e0d7e709de231daf624eb1fd80873
+ENV LOGSTASH_TARBALL="https://download.elastic.co/logstash/logstash/logstash-1.5.6.tar.gz" \
+	LOGSTASH_TARBALL_ASC="" \
+	LOGSTASH_TARBALL_SHA1="f3e4342f496e0d7e709de231daf624eb1fd80873"
 
-RUN \
-  adduser -D -S elasticsearch
-RUN \
-  mkdir -p /opt && \
-  cd /tmp && \
-  curl -L https://download.elastic.co/logstash/logstash/logstash-$LOGSTASH_VERSION.tar.gz > logstash-$LOGSTASH_VERSION.tar.gz && \
-  echo "$LOGSTASH_TAR_SHA1  logstash-$LOGSTASH_VERSION.tar.gz" | sha1sum -c - && \
-  tar -xzf logstash-$LOGSTASH_VERSION.tar.gz && \
-  rm -rf logstash-$LOGSTASH_VERSION.tar.gz && \
-  mv logstash-$LOGSTASH_VERSION /opt/logstash && \
-  ln -s /opt/logstash/bin/logstash /usr/local/bin/logstash
+RUN set -ex; \
+	\
+	if [ -z "$LOGSTASH_TARBALL_SHA1" ] && [ -z "$LOGSTASH_TARBALL_ASC" ]; then \
+		echo >&2 'error: have neither a SHA1 _or_ a signature file -- cannot verify download!'; \
+		exit 1; \
+	fi; \
+	\
+	apk add --no-cache --virtual .fetch-deps \
+		ca-certificates \
+		gnupg \
+		openssl \
+		tar \
+	; \
+	\
+	wget -O logstash.tar.gz "$LOGSTASH_TARBALL"; \
+	\
+	if [ "$LOGSTASH_TARBALL_SHA1" ]; then \
+		echo "$LOGSTASH_TARBALL_SHA1 *logstash.tar.gz" | sha1sum -c -; \
+	fi; \
+	\
+	if [ "$LOGSTASH_TARBALL_ASC" ]; then \
+		wget -O logstash.tar.gz.asc "$LOGSTASH_TARBALL_ASC"; \
+		export GNUPGHOME="$(mktemp -d)"; \
+		gpg --keyserver ha.pool.sks-keyservers.net --recv-keys "$GPG_KEY"; \
+		gpg --batch --verify logstash.tar.gz.asc logstash.tar.gz; \
+		rm -r "$GNUPGHOME" logstash.tar.gz.asc; \
+	fi; \
+	\
+	dir="$(dirname "$LOGSTASH_PATH")"; \
+	\
+	mkdir -p "$dir"; \
+	tar -xf logstash.tar.gz --strip-components=1 -C "$dir"; \
+	rm logstash.tar.gz; \
+	\
+	apk del .fetch-deps; \
+	\
+	export LS_SETTINGS_DIR="$dir/config"; \
+# if the "log4j2.properties" file exists (logstash 5.x), let's empty it out so we get the default: "logging only errors to the console"
+	if [ -f "$LS_SETTINGS_DIR/log4j2.properties" ]; then \
+		cp "$LS_SETTINGS_DIR/log4j2.properties" "$LS_SETTINGS_DIR/log4j2.properties.dist"; \
+		truncate -s 0 "$LS_SETTINGS_DIR/log4j2.properties"; \
+	fi; \
+	\
+# set up some file permissions
+	for userDir in \
+		"$dir/config" \
+		"$dir/data" \
+	; do \
+		if [ -d "$userDir" ]; then \
+			chown -R logstash:logstash "$userDir"; \
+		fi; \
+	done; \
+	\
+	logstash --version
 
 COPY docker-entrypoint.sh /
 
 ENTRYPOINT ["/docker-entrypoint.sh"]
-CMD ["logstash", "agent"]
+CMD ["-e", ""]
